---
- name: Install packages
  yum:
    name: "yum-utils"
    state: present
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: add repo
  command: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  when: 
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

