---
- name: Creates directory - /etc/docker
  file:
    path: "/etc/docker"
    state: directory
    mode: 0700

- name: Copy config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "docker.service.j2",dest: "/etc/systemd/system/docker.service" }
    - { src: "daemon.json.j2",dest: "/etc/docker/daemon.json" }
  notify: restart docker

- meta: flush_handlers
